Jenkinsfiletest

diff --git a/Jenkinsfile.kube b/Jenkinsfile.kube
--- a/Jenkinsfile.kube
+++ b/Jenkinsfile.kube
@@ -31,7 +31,7 @@ spec:
     //DOCKER_ACCT      = "hellobloom"                // Dockerhub account
     DOCKER_ACCT      = 'rcompos'                   // *** TEST REPO  ***
     IMAGE_NAME       = 'bloom-vault'               // Dockerhub image name
-    DOCKER_IMAGE     = "$DOCKER_ACCT/$IMAGE_NAME"  // Dockerhub image
+    DOCKER_IMAGE     = "${DOCKER_ACCT}/${IMAGE_NAME}"  // Dockerhub image
     DOCKERHUB_ID     = 'dockerhub-creds'           // Dockerhub credentials
     SSH_KEY          = credentials('bloom-vault-ssh-key')  // Bloom Vault ssh key
     NPMRC            = credentials('bloom-vault-npmrc')    // NPM token
@@ -44,11 +44,17 @@ spec:
       steps {
         container('docker') {
           sh """
-            echo "Installing dependencies"
-            if $DEBUG; then
-              echo "###  DEBUGGIN MODE  ###"
-              printenv
-              ls -AlF ..
+            echo "Checking envvars."
+            if ${DEBUG}; then
+              printenv; ls -AlF ..;
+            fi
+            if test -z ${SSH_KEY}; then
+              echo "ERROR: SSH_KEY must be set" 
+              exit 2
+            fi
+            if test -z ${NPMRC}; then
+              echo "ERROR: NPMRC must be set" 
+              exit 2
             fi
           """
         }
